site_name: chat-script docs

theme:
  name: "material"
  font:
    text: Quicksand
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - mkdocstrings

markdown_extensions:
  - tables

nav:
  - Welcome: index.md
  - options.md
  - architecture.md
  - reference.md