#!/usr/bin/env bash

set -euo pipefail
box() { boxes -d ansi -s $(tput cols); }
failed() {
  echo -e "\n\033[1;31mBuild failed.\033[0m"
  exit 1
}
interrupted() {
  echo -e "\n\033[1;33mInterrupted.\033[0m"
  exit 0
}

trap 'failed' ERR
trap 'interrupted' INT

echo -e "\033[1;33mruff...\033[0m"
ruff check | box

echo -e "\n\033[1;33mcoverage...\033[0m"
coverage run -m unittest 2> /dev/null | box

echo -e "\n\033[1;33mbuild...\033[0m"
nix build 2> /dev/null | box

echo -e "\n\033[1;32mBuild succeeded.\033[0m"
